/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.admin;

import backend.Compra;
import backend.GestorClientes;
import backend.GestorCompras;
import frontend.Login;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author orlandopalma
 */
public class InterfazResultadoComp extends javax.swing.JFrame {

    /**
     * Creates new form InterfazResultado
     */
    public InterfazResultadoComp() {
        initComponents();
    }

    public void rellenarTabla(Compra compra) {
        String nombresColumnas[] = {"ID Compra", "ID Cliente", "ID Película", "Fecha"};
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.setColumnIdentifiers(nombresColumnas);
        model.addRow(new Object[]{compra.getIdCompra(), compra.getIdCliente(), compra.getIdPelicula(), compra.getFecha()});
        tablaCompras.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        titulo1 = new javax.swing.JLabel();
        VolverButton = new javax.swing.JButton();
        panelTitulo = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBackground(new java.awt.Color(230, 230, 230));

        tablaCompras.setBackground(new java.awt.Color(230, 230, 230));
        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCompras.setShowGrid(false);
        jScrollPane3.setViewportView(tablaCompras);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 80));

        titulo1.setBackground(new java.awt.Color(242, 167, 48));
        titulo1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(242, 167, 48));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("Volver");
        jPanel1.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 550, 200, 50));

        VolverButton.setBackground(new java.awt.Color(71, 160, 209));
        VolverButton.setBorder(null);
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VolverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 160, 50));

        panelTitulo.setBackground(new java.awt.Color(71, 160, 209));
        panelTitulo.setPreferredSize(new java.awt.Dimension(667, 102));
        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo2.setBackground(new java.awt.Color(242, 167, 48));
        titulo2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 54)); // NOI18N
        titulo2.setForeground(new java.awt.Color(242, 167, 48));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("<html><center></center></html>");
        panelTitulo.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 102));

        jPanel1.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 390, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/usuario/media/Imagen de fondo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 568, 606));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        titulo2.setText("<html><center>ID: " + InterfazAdmin.ID + "</center></html>");
        if ((Login.gestorCompras.getCompras().get(Long.parseLong(InterfazAdmin.ID))) != null && InterfazAdmin.ID != null) {
            rellenarTabla(Login.gestorCompras.getCompras().get(Long.parseLong(InterfazAdmin.ID)));
        } else {
            JOptionPane.showMessageDialog(rootPane, "La compra no ha sido encontrada", "Error", HEIGHT);
            this.dispose();
            new InterfazAdmin().setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        this.dispose();
        new InterfazAdmin().setVisible(true);
    }//GEN-LAST:event_VolverButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazResultadoComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazResultadoComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazResultadoComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazResultadoComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazResultadoComp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VolverButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
