/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.admin;

import frontend.Login;
import static frontend.Login.gestorPeliculas;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAdmin
     */
    public Reportes() {
        initComponents();
        //this.setLocationRelativeTo(null);
    }
    static String ID;

    public void rellenarTablaPeliculas() {
        String nombresColumnas[] = {"ID", "Titulo", "Director", "Año", "Genero", "Precio", "Ventas"};
        List<String> listaPeliculas = new ArrayList<>(Login.generadorReporte.generarReportePeliculas(gestorPeliculas));
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.setColumnIdentifiers(nombresColumnas);
        for (String pelicula : listaPeliculas) {
            model.addRow(new Object[]{Long.parseLong(pelicula.split(",")[0]), pelicula.split(",")[1], pelicula.split(",")[2], Integer.parseInt(pelicula.split(",")[3]), pelicula.split(",")[4], Double.parseDouble(pelicula.split(",")[5]), Integer.parseInt(pelicula.split(",")[6])});
        }
        tabla.setModel(model);
    }

    public void rellenarTablaCompras() {
        String nombresColumnas[] = {"Mes", "Número de ventas"};
        List<String> listaCompras = new ArrayList<>(Login.generadorReporte.generarReporteVentas(Login.gestorCompras));
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.setColumnIdentifiers(nombresColumnas);
        for (String compra : listaCompras) {
            model.addRow(new Object[]{compra.split(",")[0], Long.parseLong(compra.split(",")[1])});
        }
        tabla.setModel(model);
    }

    public void rellenarTablaCliente() {
        String nombresColumnas[] = {"ID", "Nombre", "Email", "Dirección", "Número de Compras"};
        List<String> listaClientes = new ArrayList<>(Login.generadorReporte.generarReporteClientes(Login.gestorCliente));
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.setColumnIdentifiers(nombresColumnas);
        for (String cliente : listaClientes) {
            model.addRow(new Object[]{Long.parseLong(cliente.split(",")[0]), cliente.split(",")[1], cliente.split(",")[2], cliente.split(",")[3], Integer.parseInt(cliente.split(",")[4])});
        }
        tabla.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ScrollCliente = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        titulo1 = new javax.swing.JLabel();
        VolverButton = new javax.swing.JButton();
        VerPeliculasText = new javax.swing.JLabel();
        VerClientesText = new javax.swing.JLabel();
        VerClientesButton = new javax.swing.JButton();
        VerPeliculasButton = new javax.swing.JButton();
        VerVentas = new javax.swing.JLabel();
        VerVentassButton = new javax.swing.JButton();
        panelTitulo = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollCliente.setBackground(new java.awt.Color(230, 230, 230));

        tabla.setBackground(new java.awt.Color(230, 230, 230));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setShowGrid(false);
        ScrollCliente.setViewportView(tabla);

        jPanel1.add(ScrollCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, 240));

        titulo1.setBackground(new java.awt.Color(242, 167, 48));
        titulo1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(242, 167, 48));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("Volver");
        jPanel1.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 550, 200, 50));

        VolverButton.setBackground(new java.awt.Color(71, 160, 209));
        VolverButton.setBorder(null);
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VolverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 160, 50));

        VerPeliculasText.setBackground(new java.awt.Color(242, 167, 48));
        VerPeliculasText.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        VerPeliculasText.setForeground(new java.awt.Color(242, 167, 48));
        VerPeliculasText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VerPeliculasText.setText("<html><center>Peliculas mas vendidas</center></html>");
        jPanel1.add(VerPeliculasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 50));

        VerClientesText.setBackground(new java.awt.Color(242, 167, 48));
        VerClientesText.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        VerClientesText.setForeground(new java.awt.Color(242, 167, 48));
        VerClientesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VerClientesText.setText("<html><center>Mejores Clientes</center></html>");
        jPanel1.add(VerClientesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 50));

        VerClientesButton.setBackground(new java.awt.Color(71, 160, 209));
        VerClientesButton.setBorder(null);
        VerClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerClientesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VerClientesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 220, 70));

        VerPeliculasButton.setBackground(new java.awt.Color(71, 160, 209));
        VerPeliculasButton.setBorder(null);
        VerPeliculasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPeliculasButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VerPeliculasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 220, 70));

        VerVentas.setBackground(new java.awt.Color(242, 167, 48));
        VerVentas.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        VerVentas.setForeground(new java.awt.Color(242, 167, 48));
        VerVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VerVentas.setText("<html><center>Ventas Por Tiempo</center></html>");
        jPanel1.add(VerVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 210, 50));

        VerVentassButton.setBackground(new java.awt.Color(71, 160, 209));
        VerVentassButton.setBorder(null);
        VerVentassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerVentassButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VerVentassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 220, 70));

        panelTitulo.setBackground(new java.awt.Color(71, 160, 209));
        panelTitulo.setPreferredSize(new java.awt.Dimension(667, 102));
        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo2.setBackground(new java.awt.Color(242, 167, 48));
        titulo2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 54)); // NOI18N
        titulo2.setForeground(new java.awt.Color(242, 167, 48));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("<html><center>Reportes</center></html>");
        panelTitulo.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 102));

        jPanel1.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 390, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/usuario/media/Imagen de fondo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 960, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 775, 606));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        this.setVisible(false);
        new InterfazAdmin().setVisible(true);
    }//GEN-LAST:event_VolverButtonActionPerformed

    private void VerPeliculasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPeliculasButtonActionPerformed
        ScrollCliente.setVisible(true);
        rellenarTablaPeliculas();
    }//GEN-LAST:event_VerPeliculasButtonActionPerformed

    private void VerVentassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerVentassButtonActionPerformed
        ScrollCliente.setVisible(true);
        rellenarTablaCompras();    }//GEN-LAST:event_VerVentassButtonActionPerformed

    private void VerClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerClientesButtonActionPerformed
        ScrollCliente.setVisible(true);
        rellenarTablaCliente();    }//GEN-LAST:event_VerClientesButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ScrollCliente.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollCliente;
    private javax.swing.JButton VerClientesButton;
    private javax.swing.JLabel VerClientesText;
    private javax.swing.JButton VerPeliculasButton;
    private javax.swing.JLabel VerPeliculasText;
    private javax.swing.JLabel VerVentas;
    private javax.swing.JButton VerVentassButton;
    private javax.swing.JButton VolverButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
