/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.admin;

import backend.Cliente;
import backend.Compra;
import backend.GestorClientes;
import backend.GestorCompras;
import backend.Pelicula;
import frontend.Login;
import static frontend.Login.gestorPeliculas;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author orlandopalma
 */
public class VerClientes extends javax.swing.JFrame {

    /**
     * Creates new form InterfazResultado
     */
    public VerClientes() {
        initComponents();
    }

    public void rellenarTabla() {
        String nombresColumnas[] = {"ID", "Nombre", "Email", "Dirección", "Número de Compras"};
        List<Cliente> listaClientes = new ArrayList<>(Login.gestorCliente.getClientes().values());
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.setColumnIdentifiers(nombresColumnas);
        for (Cliente cliente : listaClientes) {
            model.addRow(new Object[]{cliente.getId(), cliente.getNombre(), cliente.getEmail(), cliente.getDireccion(), cliente.getNumeroDeCompras()});
        }
        tablaCompras.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ScrollCliente = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        titulo1 = new javax.swing.JLabel();
        VolverButton = new javax.swing.JButton();
        AgregarText = new javax.swing.JLabel();
        AgregarButton = new javax.swing.JButton();
        EliminarText = new javax.swing.JLabel();
        EliminarButton = new javax.swing.JButton();
        ActualizarText = new javax.swing.JLabel();
        ActualizarButton = new javax.swing.JButton();
        panelTitulo = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollCliente.setBackground(new java.awt.Color(230, 230, 230));

        tablaCompras.setBackground(new java.awt.Color(230, 230, 230));
        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCompras.setShowGrid(false);
        ScrollCliente.setViewportView(tablaCompras);

        jPanel1.add(ScrollCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 240));

        titulo1.setBackground(new java.awt.Color(242, 167, 48));
        titulo1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(242, 167, 48));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("Volver");
        jPanel1.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 550, 200, 50));

        VolverButton.setBackground(new java.awt.Color(71, 160, 209));
        VolverButton.setBorder(null);
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VolverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 160, 50));

        AgregarText.setBackground(new java.awt.Color(242, 167, 48));
        AgregarText.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        AgregarText.setForeground(new java.awt.Color(242, 167, 48));
        AgregarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarText.setText("Agregar ");
        jPanel1.add(AgregarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 200, 50));

        AgregarButton.setBackground(new java.awt.Color(71, 160, 209));
        AgregarButton.setBorder(null);
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 160, 50));

        EliminarText.setBackground(new java.awt.Color(242, 167, 48));
        EliminarText.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        EliminarText.setForeground(new java.awt.Color(242, 167, 48));
        EliminarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EliminarText.setText("Eliminar");
        jPanel1.add(EliminarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 200, 50));

        EliminarButton.setBackground(new java.awt.Color(71, 160, 209));
        EliminarButton.setBorder(null);
        EliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 160, 50));

        ActualizarText.setBackground(new java.awt.Color(242, 167, 48));
        ActualizarText.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        ActualizarText.setForeground(new java.awt.Color(242, 167, 48));
        ActualizarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActualizarText.setText("Actualizar");
        jPanel1.add(ActualizarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 200, 50));

        ActualizarButton.setBackground(new java.awt.Color(71, 160, 209));
        ActualizarButton.setBorder(null);
        ActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ActualizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 160, 50));

        panelTitulo.setBackground(new java.awt.Color(71, 160, 209));
        panelTitulo.setPreferredSize(new java.awt.Dimension(667, 102));
        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo2.setBackground(new java.awt.Color(242, 167, 48));
        titulo2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 54)); // NOI18N
        titulo2.setForeground(new java.awt.Color(242, 167, 48));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("<html><center>Clientes</center></html>");
        panelTitulo.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 102));

        jPanel1.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 390, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/usuario/media/Imagen de fondo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        rellenarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        this.setVisible(false);
        new InterfazAdmin().setVisible(true);
    }//GEN-LAST:event_VolverButtonActionPerformed

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed

        String idStr = (JOptionPane.showInputDialog("Ingrese el ID: "));
        Long id;
        String nombre;
        String email;
        String direccion;
        if (idStr == null) {
        } else {
            try {
                id = Long.parseLong(idStr);
                if (Login.gestorCliente.getClientes().get(id) == null) {
                    nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");
                    if (nombre != null) {
                        email = JOptionPane.showInputDialog("Ingrese el email: ");
                        if (email != null) {
                            direccion = JOptionPane.showInputDialog("Ingrese la dirección: ");
                            if (direccion != null) {
                                Cliente cli = new Cliente(id, nombre, email, direccion, 0);
                                Login.gestorCliente.agregar(cli);
                                rellenarTabla();
                            }
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Usuario con ID " + id + " ya existe", "Error", 0);
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error", "Error", 0);
            }
        }


    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void EliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarButtonActionPerformed
        String idStr = (JOptionPane.showInputDialog("Ingrese el ID: "));
        if (idStr != null) {
            Long id = Long.valueOf(idStr);
            if (Login.gestorCliente.getClientes().get(id) == null) {
                JOptionPane.showMessageDialog(rootPane, "Usuario con ID " + id + " no existe", "Error", 0);
            } else {
                try {
                    Login.gestorCliente.eliminar(id);
                    rellenarTabla();
                } catch (IOException ex) {
                    Logger.getLogger(VerClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_EliminarButtonActionPerformed

    private void ActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtonActionPerformed
        Long id;
        String nombre;
        String email;
        String direccion;
        int numeroDeCompras;
        String idStr = (JOptionPane.showInputDialog("Ingrese el ID: "));
        if (idStr != null) {
            id = Long.valueOf(idStr);
            if (Login.gestorCliente.getClientes().get(id) == null) {
                JOptionPane.showMessageDialog(rootPane, "Usuario con ID " + id + " no existe", "Error", 0);
            } else {
                try {
                    nombre = JOptionPane.showInputDialog("Ingrese el nombre: ", Login.gestorCliente.getClientes().get(id).getNombre());
                    if (nombre != null) {
                        email = JOptionPane.showInputDialog("Ingrese el email: ", Login.gestorCliente.getClientes().get(id).getEmail());
                        if (email != null) {
                            direccion = JOptionPane.showInputDialog("Ingrese la dirección: ", Login.gestorCliente.getClientes().get(id).getDireccion());
                            if (direccion != null) {
                                Login.gestorCliente.actualizar(id, nombre + "," + email + "," + direccion + "," + Login.gestorCliente.getClientes().get(id).getNumeroDeCompras() + "\n");
                                rellenarTabla();
                            }
                        }
                    }
                    rellenarTabla();
                } catch (IOException ex) {
                    Logger.getLogger(VerClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_ActualizarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JLabel ActualizarText;
    private javax.swing.JButton AgregarButton;
    private javax.swing.JLabel AgregarText;
    private javax.swing.JButton EliminarButton;
    private javax.swing.JLabel EliminarText;
    private javax.swing.JScrollPane ScrollCliente;
    private javax.swing.JButton VolverButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
