/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.admin;

import backend.Pelicula;
import frontend.Login;
import java.io.IOException;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author orlandopalma
 */
public class VerPeliculas extends javax.swing.JFrame {

    /**
     * Creates new form InterfazResultado
     */
    public VerPeliculas() {
        initComponents();
    }

    public void rellenarTabla() {
        String nombresColumnas[] = {"ID", "Titulo", "Director", "Año", "Genero", "Precio", "Numero de Ventas"};
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.setColumnIdentifiers(nombresColumnas);
        for (Map.Entry<Long, Pelicula> entry : Login.gestorPeliculas.getPeliculas().entrySet()) {
            Pelicula pelicula = entry.getValue();
            model.addRow(new Object[]{pelicula.getId(), pelicula.getTitulo(), pelicula.getDirector(), pelicula.getYear(), pelicula.getGenero(), pelicula.getPrecio(), pelicula.getNumeroDeVentas()});
        }
        tablaPeliculas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ScrollCliente = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();
        EliminarText = new javax.swing.JLabel();
        ActualizarText = new javax.swing.JLabel();
        AgregarText = new javax.swing.JLabel();
        ActualizarButton = new javax.swing.JButton();
        EliminarButton = new javax.swing.JButton();
        AgregarButton = new javax.swing.JButton();
        titulo1 = new javax.swing.JLabel();
        VolverButton = new javax.swing.JButton();
        panelTitulo = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollCliente.setBackground(new java.awt.Color(230, 230, 230));

        tablaPeliculas.setBackground(new java.awt.Color(230, 230, 230));
        tablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPeliculas.setShowGrid(false);
        ScrollCliente.setViewportView(tablaPeliculas);

        jPanel1.add(ScrollCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 240));

        EliminarText.setBackground(new java.awt.Color(242, 167, 48));
        EliminarText.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        EliminarText.setForeground(new java.awt.Color(242, 167, 48));
        EliminarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EliminarText.setText("Eliminar");
        jPanel1.add(EliminarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 200, 50));

        ActualizarText.setBackground(new java.awt.Color(242, 167, 48));
        ActualizarText.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        ActualizarText.setForeground(new java.awt.Color(242, 167, 48));
        ActualizarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActualizarText.setText("Actualizar");
        jPanel1.add(ActualizarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 200, 50));

        AgregarText.setBackground(new java.awt.Color(242, 167, 48));
        AgregarText.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        AgregarText.setForeground(new java.awt.Color(242, 167, 48));
        AgregarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarText.setText("Agregar ");
        jPanel1.add(AgregarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 200, 50));

        ActualizarButton.setBackground(new java.awt.Color(71, 160, 209));
        ActualizarButton.setBorder(null);
        ActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ActualizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 160, 50));

        EliminarButton.setBackground(new java.awt.Color(71, 160, 209));
        EliminarButton.setBorder(null);
        EliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 160, 50));

        AgregarButton.setBackground(new java.awt.Color(71, 160, 209));
        AgregarButton.setBorder(null);
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 160, 50));

        titulo1.setBackground(new java.awt.Color(242, 167, 48));
        titulo1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(242, 167, 48));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("Volver");
        jPanel1.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 550, 200, 50));

        VolverButton.setBackground(new java.awt.Color(71, 160, 209));
        VolverButton.setBorder(null);
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VolverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 160, 50));

        panelTitulo.setBackground(new java.awt.Color(71, 160, 209));
        panelTitulo.setPreferredSize(new java.awt.Dimension(667, 102));
        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo2.setBackground(new java.awt.Color(242, 167, 48));
        titulo2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 54)); // NOI18N
        titulo2.setForeground(new java.awt.Color(242, 167, 48));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("<html><center>Peliculas</center></html>");
        panelTitulo.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 102));

        jPanel1.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 390, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/usuario/media/Imagen de fondo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 568, 606));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        rellenarTabla();

    }//GEN-LAST:event_formWindowOpened

    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        this.setVisible(false);
        new InterfazAdmin().setVisible(true);
    }//GEN-LAST:event_VolverButtonActionPerformed

    private void ActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtonActionPerformed
        try {
            long id = (long) tablaPeliculas.getModel().getValueAt(tablaPeliculas.getSelectedRow(), 0);
            try {
                String titulo = JOptionPane.showInputDialog(null, "Ingrese el titulo de la pelicula: ", "Actualizar Pelicula", JOptionPane.QUESTION_MESSAGE);
                if (titulo == null || titulo.isEmpty() || titulo.isBlank()) {
                    titulo = (String) tablaPeliculas.getModel().getValueAt(tablaPeliculas.getSelectedRow(), 1);
                }
                String director = JOptionPane.showInputDialog(null, "Ingrese el nombre del director: ", "Actualizar Pelicula", JOptionPane.QUESTION_MESSAGE);
                if (director == null || director.isEmpty() || director.isBlank()) {
                    director = (String) tablaPeliculas.getModel().getValueAt(tablaPeliculas.getSelectedRow(), 2);
                }
                String year = JOptionPane.showInputDialog(null, "Ingrese el año de lanzamiento de la pelicula: ", "Actualizar Pelicula", JOptionPane.QUESTION_MESSAGE);
                if (year == null || year.isEmpty() || year.isBlank()) {
                    year = (String) tablaPeliculas.getModel().getValueAt(tablaPeliculas.getSelectedRow(), 3);
                }
                String genero = JOptionPane.showInputDialog(null, "Ingrese el genero de la pelicula: ", "Actualizar Pelicula", JOptionPane.QUESTION_MESSAGE);
                if (genero == null || genero.isEmpty() || genero.isBlank()) {
                    genero = (String) tablaPeliculas.getModel().getValueAt(tablaPeliculas.getSelectedRow(), 4);
                }
                String precio = JOptionPane.showInputDialog(null, "Ingrese el preicio de la pelicula: ", "Actualizar Pelicula", JOptionPane.QUESTION_MESSAGE);
                if (precio == null || precio.isEmpty() || precio.isBlank()) {
                    precio = (String) tablaPeliculas.getModel().getValueAt(tablaPeliculas.getSelectedRow(), 5);
                }
                Login.gestorPeliculas.actualizar(id, titulo + "," + director + "," + year + "," + genero + "," + precio + "," + Login.gestorPeliculas.getPeliculas().get(id).getNumeroDeVentas());
                rellenarTabla();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error all actualizar los datos", "Error", 0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay cliente seleccionado", "Error", 0);
        }
    }//GEN-LAST:event_ActualizarButtonActionPerformed

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed
        String idStr = (JOptionPane.showInputDialog(null, "Ingrese el ID: ", "Agregar Pelicula", JOptionPane.QUESTION_MESSAGE));
        Long id;
        String titulo;
        String director;
        int year;
        String genero;
        double precio;
        if (idStr != null) {
            try {
                id = Long.parseLong(idStr);
                if (Login.gestorPeliculas.getPeliculas().get(id) == null) {
                    titulo = JOptionPane.showInputDialog(null,"Ingrese el título: ", "Agregar Pelicula", JOptionPane.QUESTION_MESSAGE);
                    if (titulo != null) {
                        director = JOptionPane.showInputDialog(null, "Ingrese el director: ", "Agregar Pelicula", JOptionPane.QUESTION_MESSAGE);
                        if (director != null) {
                            String yearStr = JOptionPane.showInputDialog(null, "Ingrese el año: ", "Agregar Pelicula", JOptionPane.QUESTION_MESSAGE);
                            if (yearStr != null) {
                                try {
                                    year = Integer.parseInt(yearStr);
                                    String generoStr = JOptionPane.showInputDialog(null, "Ingrese el género: ", "Agregar Pelicula", JOptionPane.QUESTION_MESSAGE);
                                    if (generoStr != null) {
                                        genero = generoStr;
                                        String precioStr = JOptionPane.showInputDialog(null, "Ingrese el precio: ", "Agregar Pelicula", JOptionPane.QUESTION_MESSAGE);
                                        if (precioStr != null) {
                                            try {
                                                precio = Double.parseDouble(precioStr);
                                                Pelicula peli = new Pelicula(id, titulo, director, year, genero, precio, 0);
                                                Login.gestorPeliculas.agregar(peli);
                                                rellenarTabla();
                                            } catch (Exception e) {
                                                JOptionPane.showMessageDialog(rootPane, "Error al ingresar el precio.", "Error", JOptionPane.ERROR_MESSAGE);
                                            }

                                        }
                                    }
                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(rootPane, "Error al ingresar el año.", "Error", JOptionPane.ERROR_MESSAGE);
                                }
                            }
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Pelicula con ID " + id + " ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error al ingresar el ID", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void EliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarButtonActionPerformed
        try {
            long id = (long) tablaPeliculas.getModel().getValueAt(tablaPeliculas.getSelectedRow(), 0);
            try {
                Login.gestorPeliculas.eliminar((long) id);
                rellenarTabla();
            } catch (IOException ex) {
                System.out.println("dojoda 1");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay pelicula seleccionada", "Error", 0);
        }
    }//GEN-LAST:event_EliminarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerPeliculas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerPeliculas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerPeliculas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerPeliculas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JLabel ActualizarText;
    private javax.swing.JButton AgregarButton;
    private javax.swing.JLabel AgregarText;
    private javax.swing.JButton EliminarButton;
    private javax.swing.JLabel EliminarText;
    private javax.swing.JScrollPane ScrollCliente;
    private javax.swing.JButton VolverButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tablaPeliculas;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
