/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.usuario;

/**
 *
 * @author sebas
 */
public class Catalogo extends javax.swing.JFrame {

    /**
     * Creates new form Catalogo
     */
    public Catalogo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new FondoPanel();
        panelNavegable = new javax.swing.JPanel();
        panelTituloCatalogo = new javax.swing.JPanel();
        tituloCatalogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNavegable.setPreferredSize(new java.awt.Dimension(91, 645));

        javax.swing.GroupLayout panelNavegableLayout = new javax.swing.GroupLayout(panelNavegable);
        panelNavegable.setLayout(panelNavegableLayout);
        panelNavegableLayout.setHorizontalGroup(
            panelNavegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );
        panelNavegableLayout.setVerticalGroup(
            panelNavegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        panelFondo.add(panelNavegable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 37, -1, -1));

        panelTituloCatalogo.setBackground(new java.awt.Color(71, 160, 209));
        panelTituloCatalogo.setPreferredSize(new java.awt.Dimension(473, 101));

        tituloCatalogo.setBackground(new java.awt.Color(242, 167, 48));
        tituloCatalogo.setFont(new java.awt.Font("Lucida Sans", 1, 54)); // NOI18N
        tituloCatalogo.setForeground(new java.awt.Color(242, 167, 48));
        tituloCatalogo.setText("CATALOGO");

        javax.swing.GroupLayout panelTituloCatalogoLayout = new javax.swing.GroupLayout(panelTituloCatalogo);
        panelTituloCatalogo.setLayout(panelTituloCatalogoLayout);
        panelTituloCatalogoLayout.setHorizontalGroup(
            panelTituloCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloCatalogoLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(tituloCatalogo)
                .addGap(76, 76, 76))
        );
        panelTituloCatalogoLayout.setVerticalGroup(
            panelTituloCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloCatalogoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tituloCatalogo)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelFondo.add(panelTituloCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 47, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelNavegable;
    private javax.swing.JPanel panelTituloCatalogo;
    private javax.swing.JLabel tituloCatalogo;
    // End of variables declaration//GEN-END:variables
}
